### PR TITLE
Add linters to repo

### PR DESCRIPTION
**Pull request by tajemouti**
1. Added a .gitignore to the root directory
2. Created a .github/workflows directory and added linters.yml
3. Added .hintrc file to the root directory
4. Added .stylelintrc file to the root directory
5. Add MIT.md license
6. Edited README.md and MIT.md files
7. Added and edited index.html, style.css, and test.md files
8. Tested with Webhint and Stylehint
9. Fixed indentation errors in the style.css file
10. Added JSON file to .gitignore
11. Added metadata to the index.html file

### CODE REVIEW

**Review by LionRouge1 — CHANGES_REQUESTED** [review]
Hi @tajemouti, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights
- Good PR :heavy_check_mark: 
- Good commit :heavy_check_mark: 
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
- [x] Nice work using the Microverse template for your README file :clap:  However some of the sections are missing. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your README file, only the **FAQ** section is optional.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tajemouti** [comment]
Hi there..
Thank you for your fast and helpful feedback..
Have a great day..

**Comment by tajemouti** [comment]
@LionRouge1 
Thank you again for the fast review and feedback.. 
I need to ask you about this..
image
I don't know if I need to add the 2 first lines to the README file.. Or if there's something wrong with the repo name and its description.. Would you please enlighten me about this..

**Review by aamirkhan2478 — APPROVED** [review]
Hi @tajemouti , 

GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
